### ISSUE TITLE
Daydream support

### ISSUE THREAD

**Issue by kmare** [michaltakac/mathworldvr#11]
**Description:**
Add support for the daydream platform

- Platform / Device:
Android, Daydream view + daydream controller

- Reproducible Code Snippet or URL:

**Comment by michaltakac** [comment]
Since I don't have access to android device nor daydream headset + controller, calling for help here.

Help from someone with Daydream is much appreciated!

**Comment by michaltakac** [comment]
https://github.com/michaltakac/mathworldvr/commit/a67f775ecade34ae827ca14be29ed46830266499
