### ISSUE TITLE
The site can’t be reached

### ISSUE THREAD

**Issue by mikelortega** [michaltakac/mathworldvr#12]
I'm trying to visit [http://vr.sld.gs/mathworldvr/](http://vr.sld.gs/mathworldvr/) but it seems something doesn't work.

**Comment by michaltakac** [comment]
@mikelortega uploaded to new domain: https://mathworldvr.michaltakac.com.

**Comment by mikelortega** [comment]
Thank you! Very interesting project :)

**Comment by michaltakac** [comment]
Thanks :)
